[tool.black]
line-length = 99
target-version = ["py36", "py37"]
exclude = '''
/(
    \.git|.venv|target
)/
'''

[build-system]
requires = ["setuptools", "wheel", "setuptools-rust"]

[tool.isort]
from_first = true
